/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AdminSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'id', 'name', 'password', 'updatedAt', 'username'] as const
  $columns = AdminSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
}

export class BannerSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'image', 'isActive', 'subtitle', 'title', 'travelPackageId', 'updatedAt'] as const
  $columns = BannerSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare isActive: boolean | null
  @column()
  declare subtitle: string | null
  @column()
  declare title: string
  @column()
  declare travelPackageId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReviewSchema extends BaseModel {
  static $columns = ['comment', 'createdAt', 'customerName', 'customerPhoto', 'id', 'rating', 'travelPackageId', 'updatedAt'] as const
  $columns = ReviewSchema.$columns
  @column()
  declare comment: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare customerName: string
  @column()
  declare customerPhoto: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare rating: number
  @column()
  declare travelPackageId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TravelPackageSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'destination', 'duration', 'facilities', 'id', 'image', 'isActive', 'price', 'quota', 'title', 'updatedAt'] as const
  $columns = TravelPackageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string
  @column()
  declare destination: string
  @column()
  declare duration: string | null
  @column()
  declare facilities: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string
  @column()
  declare isActive: boolean | null
  @column()
  declare price: string
  @column()
  declare quota: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
